name: Tagify
version: 1.0.0
description: Lightweight and efficient Tags input plugin for Flextype.
icon:
  name: flag
  set: bootstrap
author:
  name: Sergey Romanenko
  email: sergey.romanenko@flextype.org
  url: https://flextype.org
homepage: https://github.com/flextype-plugins/tagify
bugs: https://github.com/flextype-plugins/tagify/issues
license: MIT

dependencies:
  flextype: 0.9.16
  twig: '>=2.0.0'
  blueprints: '>=1.0.0'
